name: Combine pushed keys into combined.txt

# Trigger the workflow on push to any branch
on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Run the shell script
    - name: Run shell script
      run: |
        chmod +x ./join.sh
        ./join.sh

    # Configure Git
    - name: Set up Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    # Commit the new file
    - name: Commit new file
      run: |
        git add built/combined.txt
        git commit -m "Add build file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
