name: Combine pushed keys into combined.txt

# Trigger the workflow on push to any branch
on: 
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Run the shell script
    - name: Run shell script
      run: |
        chmod +x ./join.sh
        ./join.sh

    # Publish the artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: my-artifact
        path: output/combined.txt  # Replace with the actual path to your artifact

